import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

import Parse1 from "./services/parse";

export default function Home() {
  const gameScore = new Parse1.Object("GameScore");

  gameScore.set("score", 1337);
  gameScore.set("playerName", "Sean Plott");
  gameScore.set("cheatMode", false);

  gameScore.save().then(
    (gameScore) => {
      // Execute any logic that should take place after the object is saved.
      console.log("New object created with objectId: " + gameScore.id);
    },
    (error) => {
      // Execute any logic that should take place if the save fails.
      // error is a Parse.Error with an error code and message.
      console.log(
        "Failed to create new object, with error code: " + error.message
      );
    }
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Craft Next App</title>
        <meta name="description" content="Generated by Craft" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Image src="/craft.png" alt="Craft logo" width={222} height={90} />
          <h1
            className={styles.title}
            style={{
              marginLeft: "20px",
              marginRight: "20px",
              marginTop: "30px",
            }}
          ></h1>
          <Image
            src="/nextjs.png"
            alt="Next.js logo"
            width={222}
            height={150}
          />
        </div>
        <h1 className={styles.title}>Welcome to your personal site</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>src/pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <span style={{ marginTop: "30px" }}>Powered by </span>
        <span className={styles.logo}>
          <Image
            src="/brewery.png"
            alt="The Brewery Logo"
            width={115}
            height={46}
          />
        </span>
      </footer>
    </div>
  );
}
